### ISSUE TITLE
Cannot read property 'posts' of undefined

### ISSUE THREAD

**Issue by hareendras** [ruial/9gag#1]
Hi,

This stopped working

 TypeError: Cannot read property 'posts' of undefined
     at Object.readPosts (/app/node_modules/9gag/src/mapper.js:37:25)
     at Scraper.scrap (/app/node_modules/9gag/src/scraper.js:38:28)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ruial** [comment]
I have fixed the issue, all tests are passing now.

**Comment by hareendras** [comment]
Hi,

This works fine now.
